-
    version: 1.0.{build}
    clone_depth: 15

    environment:
        matrix:
            - MATRIX_ENV: "first-flavor"
            - MATRIX_ENV: "second-flavor"

    install:
        - ps: >-
            $ps_var = 'install'

            $env:env_var = 'install'

            Write-Host "%MATRIX_ENV%: $($env:MATRIX_ENV); ps_var: $ps_var; env_var $($env:env_var)"

    before_build:
        - ps: >-
            Write-Host "%MATRIX_ENV%: $($env:MATRIX_ENV); ps_var: $ps_var; env_var $($env:env_var)"

            $ps_var = 'bb'

            $env:env_var = 'bb'

            Write-Host "%MATRIX_ENV%: $($env:MATRIX_ENV); ps_var: $ps_var; env_var $($env:env_var)"


    build_script:
        - ps: >-
            Write-Host "%MATRIX_ENV%: $($env:MATRIX_ENV); ps_var: $ps_var; env_var $($env:env_var)"

            $ps_var = 'bs'

            $env:env_var = 'bs'

            Write-Host "%MATRIX_ENV%: $($env:MATRIX_ENV); ps_var: $ps_var; env_var $($env:env_var)"

    test_script:
        - ps: >-
            Write-Host "%MATRIX_ENV%: $($env:MATRIX_ENV); ps_var: $ps_var; env_var $($env:env_var)"

            $ps_var = 'ts'

            $env:env_var = 'ts'

            Write-Host "%MATRIX_ENV%: $($env:MATRIX_ENV); ps_var: $ps_var; env_var $($env:env_var)"
